export interface MenuItem {
  id: string
  name: string
  price: number
  category: string
  note?: string
}
export const MENU_ITEMS: MenuItem[] = [
  { id: 'w1', name: 'Hot Buffalo Wings', price: 999, category: 'Wings & Fried Chicken' },
  { id: 'w2', name: 'Crispy Wings', price: 650, category: 'Wings & Fried Chicken' },
  { id: 'w3', name: 'Salsa Wings', price: 699, category: 'Wings & Fried Chicken' },
  { id: 'w4', name: 'Chicken Strips', price: 580, category: 'Wings & Fried Chicken' },
  { id: 'w5', name: 'Fried Chicken Chest Piece', price: 350, category: 'Wings & Fried Chicken' },
  { id: 'w6', name: 'Fried Chicken Leg Piece', price: 350, category: 'Wings & Fried Chicken' },
  { id: 's1', name: 'Chinese Special Soup Family', price: 1599, category: 'Soups' },
  { id: 's2', name: 'Chinese Special Soup Single', price: 550, category: 'Soups' },
  { id: 's3', name: 'Chicken Corn Soup Family', price: 1299, category: 'Soups' },
  { id: 's4', name: 'Chicken Corn Soup Single', price: 299, category: 'Soups' },
  { id: 'b1', name: 'Black Diamond Patty Burger', price: 999, category: 'Burgers', note: 'Double patty Chicken & Beef' },
  { id: 'b2', name: 'Pink Bun Burger', price: 999, category: 'Burgers', note: 'Double patty Chicken & Beef' },
  { id: 'b3', name: 'Crispy Zinger Burger', price: 380, category: 'Burgers' },
  { id: 'b4', name: 'Zinger Burger', price: 480, category: 'Burgers' },
  { id: 'b5', name: 'Grilled Chicken Burger', price: 699, category: 'Burgers' },
  { id: 'b6', name: 'Cheese Mushroom Burger', price: 750, category: 'Burgers' },
  { id: 'b7', name: 'Crunchy Chicken Burger', price: 750, category: 'Burgers' },
  { id: 'b8', name: 'Grilled Chicken Jalapeno Burger', price: 599, category: 'Burgers' },
  { id: 'f1', name: 'Nachos', price: 699, category: 'Fries & Nachos' },
  { id: 'f2', name: 'Plain Fries', price: 300, category: 'Fries & Nachos' },
  { id: 'f3', name: 'Loaded Fries', price: 699, category: 'Fries & Nachos' },
  { id: 'f4', name: 'Masala Fries', price: 399, category: 'Fries & Nachos' },
  { id: 'f5', name: 'Garlic Mayo Fries', price: 499, category: 'Fries & Nachos' },
  { id: 'f6', name: 'Cheese Fries', price: 650, category: 'Fries & Nachos' },
  { id: 'pa1', name: 'Chicken Mushroom Panini', price: 999, category: 'Pasta' },
  { id: 'pa2', name: 'Penne Arrabbiata Pasta', price: 1099, category: 'Pasta' },
  { id: 'pa3', name: 'Alfredo Pasta', price: 980, category: 'Pasta' },
  { id: 'pa4', name: 'Chicken Lasagna', price: 999, category: 'Pasta' },
  { id: 'p0', name: 'Deep Dish Pizza', price: 2400, category: 'Pizzas' },
  { id: 'p1', name: 'Crown Crust Pizza', price: 799, category: 'Pizzas', note: 'S/M/L/F: 799/1119/1999/2450' },
  { id: 'p2', name: 'Doner Pizza', price: 799, category: 'Pizzas', note: 'S/M/L/F: 799/1299/2000/2499' },
  { id: 'p3', name: 'Malai Pizza', price: 800, category: 'Pizzas', note: 'S/M/L/F: 800/1300/2199/2600' },
  { id: 'p4', name: 'Calzone Pizza', price: 699, category: 'Pizzas', note: 'S/M/L/F: 699/1199/1999/2450' },
  { id: 'p5', name: 'Beef Pepperoni Pizza', price: 799, category: 'Pizzas', note: 'S/M/L/F: 799/1399/2200/2499' },
  { id: 'p6', name: 'Chicken Tikka Pizza', price: 600, category: 'Pizzas', note: 'S/M/L/F: 600/1100/1800/2250' },
  { id: 'p7', name: 'Beef Behari Pizza', price: 799, category: 'Pizzas', note: 'S/M/L/F: 799/1499/2299/2600' },
  { id: 'p8', name: 'Super Supreme Pizza', price: 699, category: 'Pizzas', note: 'S/M/L/F: 699/1299/2199/2600' },
  { id: 'p9', name: 'Cheese Lover Pizza', price: 699, category: 'Pizzas', note: 'S/M/L/F: 699/1199/1800/2250' },
  { id: 'sw1', name: 'Club Sandwich', price: 999, category: 'Sandwiches' },
  { id: 'sw2', name: 'Grill Sandwich', price: 899, category: 'Sandwiches' },
  { id: 'sw3', name: 'BBQ Sandwich', price: 999, category: 'Sandwiches' },
  { id: 'sw4', name: 'Mushroom Panini', price: 999, category: 'Sandwiches' },
  { id: 'sw5', name: 'Grill Chicken Panini', price: 999, category: 'Sandwiches' },
  { id: 'ch1', name: 'Chicken Chilli Dry with Rice', price: 1350, category: 'Chinese' },
  { id: 'ch2', name: 'Beef Chilli Dry with Rice', price: 1400, category: 'Chinese' },
  { id: 'ch3', name: 'Mongolian Chicken with Rice', price: 1350, category: 'Chinese' },
  { id: 'ch4', name: 'Mongolian Beef with Rice', price: 1400, category: 'Chinese' },
  { id: 'ch5', name: 'Chicken Cashew Nut with Rice', price: 1350, category: 'Chinese' },
  { id: 'ch6', name: 'Chicken Chowmein', price: 799, category: 'Chinese' },
  { id: 'ch7', name: 'Chicken Fried Rice', price: 790, category: 'Chinese' },
  { id: 'ic1', name: 'Iced Latte', price: 650, category: 'Iced Coffee' },
  { id: 'ic2', name: 'Iced Caramel Latte', price: 699, category: 'Iced Coffee' },
  { id: 'ic3', name: 'Iced Spanish Latte', price: 699, category: 'Iced Coffee' },
  { id: 'ic4', name: 'Iced Hazelnut Latte', price: 699, category: 'Iced Coffee' },
  { id: 'ic5', name: 'Iced Vanilla Latte', price: 699, category: 'Iced Coffee' },
  { id: 'ic6', name: 'Iced Mocha', price: 699, category: 'Iced Coffee' },
  { id: 'hc1', name: 'Espresso Single', price: 250, category: 'Hot Coffees' },
  { id: 'hc2', name: 'Espresso Double', price: 499, category: 'Hot Coffees' },
  { id: 'hc3', name: 'Cappuccino', price: 599, category: 'Hot Coffees' },
  { id: 'hc4', name: 'Caffe Latte', price: 599, category: 'Hot Coffees' },
  { id: 'hc5', name: 'Caramel Latte', price: 699, category: 'Hot Coffees' },
  { id: 'hc6', name: 'Spanish Latte', price: 699, category: 'Hot Coffees' },
  { id: 'hc7', name: 'Hazelnut Latte', price: 699, category: 'Hot Coffees' },
  { id: 'hc8', name: 'French Vanilla Latte', price: 699, category: 'Hot Coffees' },
  { id: 'hc9', name: 'Mocha Latte', price: 699, category: 'Hot Coffees' },
  { id: 'hc10', name: 'Black Coffee', price: 300, category: 'Hot Coffees' },
  { id: 'hc11', name: 'Americano', price: 450, category: 'Hot Coffees' },
  { id: 'hc12', name: 'Hot Chocolate', price: 699, category: 'Hot Coffees' },
  { id: 'hc13', name: 'Green Tea', price: 100, category: 'Hot Coffees' },
  { id: 'hc14', name: 'Tea Bag', price: 220, category: 'Hot Coffees' },
  { id: 'mg1', name: 'Blue Lady Margarita', price: 450, category: 'Margaritas' },
  { id: 'mg2', name: 'Pineapple Margarita', price: 450, category: 'Margaritas' },
  { id: 'mg3', name: 'Peach Margarita', price: 450, category: 'Margaritas' },
  { id: 'mg4', name: 'Pink Lady Margarita', price: 450, category: 'Margaritas' },
  { id: 'mg5', name: 'Mint Margarita', price: 299, category: 'Margaritas' },
  { id: 'mg6', name: 'Green Apple Margarita', price: 450, category: 'Margaritas' },
  { id: 'it1', name: 'Lemon Iced Tea', price: 299, category: 'Iced Tea' },
  { id: 'it2', name: 'Peach Iced Tea', price: 350, category: 'Iced Tea' },
  { id: 'fr1', name: 'Classic Frappuccino', price: 799, category: 'Frapps' },
  { id: 'fr2', name: 'Caramel Frapp', price: 799, category: 'Frapps' },
  { id: 'fr3', name: 'Cookies Cream Frapp', price: 799, category: 'Frapps' },
  { id: 'fr4', name: 'Creme Brulee Frapp', price: 799, category: 'Frapps' },
  { id: 'fr5', name: 'Chocolate Monster Frapp', price: 799, category: 'Frapps' },
  { id: 'fr6', name: 'Lotus Frapp', price: 799, category: 'Frapps' },
  { id: 'fr7', name: 'Hazelnut Frapp', price: 799, category: 'Frapps' },
  { id: 'l1', name: 'Fresh Lime', price: 199, category: 'Lemonades' },
  { id: 'l2', name: 'Green Apple', price: 450, category: 'Lemonades' },
  { id: 'l3', name: 'Strawberry', price: 450, category: 'Lemonades' },
  { id: 'l4', name: 'Peach', price: 450, category: 'Lemonades' },
  { id: 'l5', name: 'Blue Berry', price: 450, category: 'Lemonades' },
  { id: 'l6', name: 'Blue Moon', price: 450, category: 'Lemonades' },
  { id: 'bk1', name: 'Filled Donut', price: 350, category: 'Bakery' },
  { id: 'bk2', name: 'Sundas', price: 310, category: 'Bakery' },
  { id: 'bk3', name: 'Cheese Cake Slice', price: 550, category: 'Bakery' },
  { id: 'bk4', name: 'Brownie', price: 300, category: 'Bakery' },
  { id: 'bk5', name: 'Pastry', price: 300, category: 'Bakery' },
  { id: 'bk6', name: 'Ring Donut', price: 220, category: 'Bakery' },
  { id: 'bk7', name: 'Mini Three Milk Cake', price: 650, category: 'Bakery' },
  { id: 'bk8', name: 'Mini Caramel Cake', price: 650, category: 'Bakery' },
  { id: 'bk9', name: 'Bento Cake', price: 999, category: 'Bakery' },
  { id: 'bk10', name: 'Lotus Donut', price: 350, category: 'Bakery' },
  { id: 'sh1', name: 'Coconut Berry Shake', price: 595, category: 'Shakes' },
  { id: 'sh2', name: 'Blueberry Milkshake', price: 550, category: 'Shakes' },
  { id: 'sh3', name: 'Peanut Butter Milkshake', price: 599, category: 'Shakes' },
  { id: 'sh4', name: 'Nutella Chocolate Shake', price: 599, category: 'Shakes' },
  { id: 'sh5', name: 'Lotus Shake', price: 599, category: 'Shakes' },
  { id: 'sh6', name: 'Oreo Shake', price: 599, category: 'Shakes' },
  { id: 'sh7', name: 'Banana Milkshake', price: 399, category: 'Shakes' },
  { id: 'sh8', name: 'Mango Milkshake', price: 399, category: 'Shakes' },
  { id: 'sh9', name: 'Strawberry Milkshake', price: 499, category: 'Shakes' },
  { id: 'bs1', name: 'The Red Grapes', price: 650, category: 'Bar Specials' },
  { id: 'bs2', name: 'Angel Kiss', price: 650, category: 'Bar Specials' },
  { id: 'bs3', name: 'Blue Redry', price: 650, category: 'Bar Specials' },
  { id: 'bs4', name: 'Apple Mint Chiller', price: 599, category: 'Bar Specials' },
  { id: 'bs5', name: 'Berry Dazzler', price: 650, category: 'Bar Specials' },
  { id: 'bs6', name: 'Orange Sunset', price: 599, category: 'Bar Specials' },
  { id: 'bs7', name: 'Pina Colada', price: 650, category: 'Bar Specials' },
  { id: 'bs8', name: 'Strawberry Colada', price: 650, category: 'Bar Specials' },
]
